### PR TITLE
Modulesync 5.4.0

### PR DESCRIPTION
**Pull request by smortex**
#### Pull Request (PR) description

The primary goal is to check CI status…

### CODE REVIEW

**Comment by bastelfreak** [comment]
I'm not sure if/how the acceptance tests ever worked

**Comment by ekohl** [comment]
For what it's worth, I don't think this module is compatible with our standard CI. It uses a custom nodeset: in 336c0b7c80a429581d1306485eccf0b28868991b it was explicitly pinned to this setfile.

I don't have a good answer to this. It's a good question for advanced uses. For now I'd recommend not managing the GitHub action until we come up with a good solution.

**Comment by natemccurdy** [comment]
I'm hoping a release of this module soon, so I've rebased this modulesync branch since it was missing some recent updates.

**Comment by bastelfreak** [comment]
@natemccurdy if you like you can start a fresh modulesync, we've some docs about it at: https://github.com/voxpupuli/modulesync_config/#modulesync-configs

If you have quesitons feel free to ask in #voxpupuli on IRC or slack.

**Comment by natemccurdy** [comment]
@smortex FYI, this module was updated to modulesync `5.5.0` in #80

**Comment by smortex** [comment]
Great! Let's close this then!

Thank you

**Pull request closed without merging**
