### PR TITLE
Prepare for release: 1.0.0

### PR DESCRIPTION
**Pull request by natemccurdy**
#### Pull Request (PR) description
This prepares the module to be released at version `1.0.0`.

### CODE REVIEW

**Review by smortex — APPROVED** [review]
:shrug: this is okay since it's a 0.x.y…

Isn't this module ready for production? If so I would advise releasing 1.0.0 so that next releases can benefit form semver.

**Comment by natemccurdy** [comment]
> Isn't this module ready for production? If so I would advise releasing 1.0.0 so that next releases can benefit form semver.

I don't really know the history on why this isn't a 1.0.0 yet. But one thing of note is that this module has not yet been fully migrated over to Vox's modulesync. It's been tried (see some open PR's), but hasn't worked yet due to problems with acceptance testing.

Maybe that's enough reason to keep it below 1.0.0?

Also, if you think I should choose a different version to bump to, I'm happy to. But in this case, I'm doin a .z bump since all that changed was some internal organization and a bug fix around using the `field` option for v1 kv paths.

**Comment by bastelfreak** [comment]
This module is already used in production and I think nothing stops us from doing a 1.0.0 release.

**Comment by natemccurdy** [comment]
@bastelfreak Would you like me to make this the 1.0.0 release?

**Comment by bastelfreak** [comment]
yes, please do a 1.0.0 release.

**Comment by natemccurdy** [comment]
> yes, please do a 1.0.0 release.

Done 👍

**Review by treydock — APPROVED** [review]

**Review by treydock — APPROVED** [review]

**Review by bastelfreak — APPROVED** [review]

**Pull request merged**
